name: github pages

on:
  push:
    branches:
    - source

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Deploy 🚀
      uses: chabad360/hugo-gh-pages@master
      with:
        githubToken: ${{ secrets.DEPLOY_TOKEN }}
        cname: www.behavioral-ds.ml
        branch: master
        hugoVersion: 0.60.1
